// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Model.proto

package cn.jly.bigdata.flink_advanced.datastream.beans;

import com.google.protobuf.Descriptors.OneofDescriptor;
import com.google.protobuf.CodedInputStream;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WordCountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.jly.bigdata.flink_advanced.datastream.beans.WordCount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string word = 1;</code>
     * @return The word.
     */
    java.lang.String getWord();
    /**
     * <code>string word = 1;</code>
     * @return The bytes for word.
     */
    com.google.protobuf.ByteString
        getWordBytes();

    /**
     * <code>int64 count = 2;</code>
     * @return The count.
     */
    long getCount();
  }
  /**
   * Protobuf type {@code cn.jly.bigdata.flink_advanced.datastream.beans.WordCount}
   */
  public static final class WordCount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.jly.bigdata.flink_advanced.datastream.beans.WordCount)
      WordCountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WordCount.newBuilder() to construct.
    private WordCount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WordCount() {
      word_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WordCount();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WordCount(
        CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              word_ = s;
              break;
            }
            case 16: {

              count_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.jly.bigdata.flink_advanced.datastream.beans.Model.internal_static_cn_jly_bigdata_flink_advanced_datastream_beans_WordCount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.jly.bigdata.flink_advanced.datastream.beans.Model.internal_static_cn_jly_bigdata_flink_advanced_datastream_beans_WordCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount.class, cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount.Builder.class);
    }

    public static final int WORD_FIELD_NUMBER = 1;
    private volatile java.lang.Object word_;
    /**
     * <code>string word = 1;</code>
     * @return The word.
     */
    @java.lang.Override
    public java.lang.String getWord() {
      java.lang.Object ref = word_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        word_ = s;
        return s;
      }
    }
    /**
     * <code>string word = 1;</code>
     * @return The bytes for word.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWordBytes() {
      java.lang.Object ref = word_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        word_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private long count_;
    /**
     * <code>int64 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public long getCount() {
      return count_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, word_);
      }
      if (count_ != 0L) {
        output.writeInt64(2, count_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, word_);
      }
      if (count_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, count_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount)) {
        return super.equals(obj);
      }
      cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount other = (cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount) obj;

      if (!getWord()
          .equals(other.getWord())) return false;
      if (getCount()
          != other.getCount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WORD_FIELD_NUMBER;
      hash = (53 * hash) + getWord().hashCode();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCount());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.jly.bigdata.flink_advanced.datastream.beans.WordCount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.jly.bigdata.flink_advanced.datastream.beans.WordCount)
        cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.jly.bigdata.flink_advanced.datastream.beans.Model.internal_static_cn_jly_bigdata_flink_advanced_datastream_beans_WordCount_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.jly.bigdata.flink_advanced.datastream.beans.Model.internal_static_cn_jly_bigdata_flink_advanced_datastream_beans_WordCount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount.class, cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount.Builder.class);
      }

      // Construct using cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        word_ = "";

        count_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.jly.bigdata.flink_advanced.datastream.beans.Model.internal_static_cn_jly_bigdata_flink_advanced_datastream_beans_WordCount_descriptor;
      }

      @java.lang.Override
      public cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount getDefaultInstanceForType() {
        return cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount.getDefaultInstance();
      }

      @java.lang.Override
      public cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount build() {
        cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount buildPartial() {
        cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount result = new cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount(this);
        result.word_ = word_;
        result.count_ = count_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount) {
          return mergeFrom((cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount other) {
        if (other == cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount.getDefaultInstance()) return this;
        if (!other.getWord().isEmpty()) {
          word_ = other.word_;
          onChanged();
        }
        if (other.getCount() != 0L) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object word_ = "";
      /**
       * <code>string word = 1;</code>
       * @return The word.
       */
      public java.lang.String getWord() {
        java.lang.Object ref = word_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          word_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string word = 1;</code>
       * @return The bytes for word.
       */
      public com.google.protobuf.ByteString
          getWordBytes() {
        java.lang.Object ref = word_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          word_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string word = 1;</code>
       * @param value The word to set.
       * @return This builder for chaining.
       */
      public Builder setWord(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        word_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string word = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWord() {
        
        word_ = getDefaultInstance().getWord();
        onChanged();
        return this;
      }
      /**
       * <code>string word = 1;</code>
       * @param value The bytes for word to set.
       * @return This builder for chaining.
       */
      public Builder setWordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        word_ = value;
        onChanged();
        return this;
      }

      private long count_ ;
      /**
       * <code>int64 count = 2;</code>
       * @return The count.
       */
      @java.lang.Override
      public long getCount() {
        return count_;
      }
      /**
       * <code>int64 count = 2;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(long value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        
        count_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.jly.bigdata.flink_advanced.datastream.beans.WordCount)
    }

    // @@protoc_insertion_point(class_scope:cn.jly.bigdata.flink_advanced.datastream.beans.WordCount)
    private static final cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount();
    }

    public static cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WordCount>
        PARSER = new com.google.protobuf.AbstractParser<WordCount>() {
      @java.lang.Override
      public WordCount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WordCount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WordCount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WordCount> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.jly.bigdata.flink_advanced.datastream.beans.Model.WordCount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_jly_bigdata_flink_advanced_datastream_beans_WordCount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_jly_bigdata_flink_advanced_datastream_beans_WordCount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Model.proto\022.cn.jly.bigdata.flink_adva" +
      "nced.datastream.beans\"(\n\tWordCount\022\014\n\004wo" +
      "rd\030\001 \001(\t\022\r\n\005count\030\002 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_jly_bigdata_flink_advanced_datastream_beans_WordCount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_jly_bigdata_flink_advanced_datastream_beans_WordCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_jly_bigdata_flink_advanced_datastream_beans_WordCount_descriptor,
        new java.lang.String[] { "Word", "Count", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
